import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
}

// Bakes the server URL (gradle property hisab.apiUrl) into the app.
val apiUrl = providers.gradleProperty("hisab.apiUrl").orElse("")
val generatedConfigDir = layout.buildDirectory.dir("generated/hisab/kotlin")
val generateBuildConfig = tasks.register("generateBuildConfig") {
    val url = apiUrl
    val outDir = generatedConfigDir
    inputs.property("apiUrl", url)
    outputs.dir(outDir)
    doLast {
        val file = outDir.get().file("app/hisab/BuildConfig.kt").asFile
        file.parentFile.mkdirs()
        val escaped = url.get().replace("\\", "\\\\").replace("\"", "\\\"")
        file.writeText(
            """
            |package app.hisab
            |
            |// Generated by composeApp/build.gradle.kts. Do not edit.
            |object BuildConfig {
            |    const val API_URL: String = "$escaped"
            |}
            |""".trimMargin(),
        )
    }
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateBuildConfig)
            dependencies {
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.ui)
                implementation(libs.compose.material3)
                implementation(libs.compose.material.icons)
                implementation(libs.navigation.compose)
                implementation(libs.ktor.client.core)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.ktor.serialization.json)
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.kotlinx.datetime)
                implementation(libs.settings)
                implementation(libs.settings.noarg)
            }
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.settings.test)
        }
        androidMain.dependencies {
            implementation(libs.androidx.activity.compose)
            implementation(libs.ktor.client.okhttp)
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
    }
}

android {
    namespace = "app.hisab"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "app.hisab"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = 1
        versionName = "0.1.0"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
            // Signed with the debug key until a real upload key is set up
            // (see docs/RELEASE.md). Fine for testing, not for the Play Store.
            signingConfig = signingConfigs.getByName("debug")
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}
